### ISSUE TITLE
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

### ISSUE THREAD

**Issue by HuaYuXiao** [HuaYuXiao/px4ctrl#3]
```bash
hyx020222@ubuntu:~$ roslaunch uav_simulation uav_simulation.launch
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/__init__.py", line 258, in main
    args = rlutil.resolve_launch_arguments(args)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/rlutil.py", line 92, in resolve_launch_arguments
    resolved = roslib.packages.find_resource(args[0], args[1])
  File "/opt/ros/noetic/lib/python3/dist-packages/roslib/packages.py", line 519, in find_resource
    pkg_path = rospack.get_path(pkg)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 205, in get_path
    self._update_location_cache()
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 188, in _update_location_cache
    list_by_path(self._manifest_name, path, cache)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 71, in list_by_path
    root = ElementTree(None, os.path.join(d, PACKAGE_FILE))
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 555, in __init__
    self.parse(file)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

**Comment by HuaYuXiao** [comment]
这个错误表明 `roslaunch` 无法找到要启动的launch文件或者找到了文件但是无法解析。常见的原因可能是launch文件的路径错误或者文件内容格式不正确。

请确保您提供的 `uav_simulation.launch` 文件路径是正确的，并且文件内容符合ROS launch文件的语法规范。您可以打开该文件并检查其内容是否正确。通常来说，一个有效的ROS launch文件应该以 `<launch>` 标签开始，以 `</launch>` 标签结束，并且包含正确的XML格式。

如果您确认文件路径和内容都是正确的，但是仍然遇到问题，那么可能是文件本身出现了问题，您可能需要重新编写或者修复该文件。如果问题仍然存在，请提供 `uav_simulation.launch` 文件的内容，以便我们更好地帮助您解决问题。

**Comment by HuaYuXiao** [comment]
Solved in v1.1.0
